[package]
name = "somfy"
version = "0.1.0"
edition = "2018"

[dependencies]
ux = { package = "ux_serde", version = "0.2.0", features = ["serde"] }
embedded-hal = "1.0.0-rc"
rppal = { version = "0.13", features = ["hal"] }
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
clap = "3.1.5"
log = "0.4.14"
env_logger = "0.9.0"
spin_sleep = "1.1.0"
webthing = { version = "0.15.0", optional = true }
uuid = { version = "0.8.2", optional = true }
serde_json = { version = "1.0.79", optional = true }
actix-rt = { version = "2.7", optional = true }

[features]
server = ["actix-rt", "webthing", "uuid", "serde_json"]

[dev-dependencies]
tempfile = "3.3.0"

[patch.crates-io]
rppal = { git = "https://github.com/reitermarkus/rppal", branch = "hal" }
