[package]
name = "somfy"
version = "0.1.0"
edition = "2018"

[dependencies]
ux = "0.1.3"
embedded-hal = "1.0.0-alpha.4"
rppal = { features = ["hal"], git = "https://github.com/reitermarkus/rppal", branch = "embedded-hal-1.0" }
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
